### ISSUE TITLE
Archive version no longer supports 'provider' parameter

### ISSUE THREAD

**Issue by staylorx** [antoineco/aco-oracle_java#26] opened 2016-11-11 16:05 UTC
V2.7.2 pulls in the latest 1.1.2 and this version no longer supports the 'provider' parameter. I removed it manually from the download.pp file and the manifest runs as expected. 

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: no parameter named 'provider' at /etc/puppetlabs/code/environments/osb2/modules/oracle_java/manifests/download.pp:35 on Archive[/usr/java/jdk-8u111-linux-x64.rpm] at /etc/puppetlabs/code/environments/osb2/modules/oracle_java/manifests/download.pp:35 on node dosbdevadm01.dev.somecool.place
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

**Comment by staylorx** [comment] 2016-11-11 16:42
I've created a fork of this repo and simply pulled the provider parameter out since I'm always on the latest version. I'll keep going through the code until I understand what I'd break.

**Comment by antoineco** [comment] 2016-11-11 17:04
I believe this was already reported in #19 and the issue was actually specific to Puppet **Enterprise**. The outcome was that the bug which caused this issue was fixed in the upstream _puppet-archive_ module, and that the `provider` parameter **does** actually exist there even in the latest version.

I installed a fresh Puppet OSS environment on Ubuntu 16.04 and executed the module, successfully (see below). Could you tell me which OS and Puppet versions you're currently seeing this with?

## 

```
root@93a81215ff89:/# puppet -V
3.8.5

root@93a81215ff89:/# puppet module install aco-oracle_java
Notice: Preparing to install into /etc/puppet/modules ...
Notice: Downloading from https://forgeapi.puppetlabs.com ...
Notice: Installing -- do not interrupt ...
/etc/puppet/modules
└─┬ aco-oracle_java (v2.7.2)
  ├── puppet-archive (v1.1.2)
  └── puppetlabs-stdlib (v4.13.1)

root@93a81215ff89:/# puppet apply -t -e 'include oracle_java'
Info: Loading facts
Info: Loading facts
Warning: Config file /etc/puppet/hiera.yaml not found, using Hiera defaults
Notice: Compiled catalog for 93a81215ff89.local in environment production in 0.35 seconds
Info: Applying configuration version '1478883716'
Notice: /Stage[main]/Oracle_java::Download/Archive[/usr/java/jre-8u112-linux-x64.tar.gz]/ensure: download archive from http://download.oracle.com/otn-pub/java/jdk/8u112-b15/jre-8u112-linux-x64.tar.gz to /usr/java/jre-8u112-linux-x64.tar.gz and extracted in /usr/java with cleanup
Info: Class[Oracle_java::Download]: Scheduling refresh of Class[Oracle_java::Install]
Info: Class[Oracle_java::Install]: Scheduling refresh of Class[Oracle_java::Install::Targz]
Notice: /Stage[main]/Oracle_java::Install::Targz/File[/usr/java/default]/ensure: created
Notice: Finished catalog run in 82.75 seconds

root@93a81215ff89:/# /usr/java/default/bin/java -version
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)
```

**Comment by markfaine** [comment] 2016-12-06 21:43
Did you ever get to the bottom of this?  I'm also seeing this on RHEL 7 with Puppet OSS agent version  4.8.1 and a puppet server running 4.4.1.   I did not see this error on my VM which is Puppet OSS agent and server 4.8.1.  Puppet Archive is 1.1.2 on both the local VM and the RHEL 7 server.

**Comment by antoineco** [comment] 2016-12-06 22:08
I still can't reproduce this unfortunately, and it puzzles me. I really wish I could hit this issue in order to understand but as you can see below it just works for me on RHEL7 (and any other platform):

```
[root@b516b9175d29 /]# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
...
```
```
[root@b516b9175d29 /]# yum install -y http://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
...
Installed:
  puppetlabs-release-pc1.noarch 0:1.1.0-2.el7                                                                           

Complete!
```
```
[root@b516b9175d29 /]# yum install -y puppet-agent
Installed:
  puppet-agent.x86_64 0:1.8.2-1.el7                                                                                     

Complete!
```
```
[root@b516b9175d29 /]# export PATH=/opt/puppetlabs/puppet/bin:$PATH
```
```
[root@b516b9175d29 /]# puppet -V
4.8.1
```
```
[root@b516b9175d29 /]# puppet module install aco-oracle_java
Notice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...
Notice: Downloading from https://forgeapi.puppet.com ...
Notice: Installing -- do not interrupt ...
/etc/puppetlabs/code/environments/production/modules
└─┬ aco-oracle_java (v2.7.2)
  ├── puppet-archive (v1.1.2)
  └── puppetlabs-stdlib (v4.13.1)
```
```
[root@b516b9175d29 /]# puppet apply -t -e 'include oracle_java'
Info: Loading facts
...
Info: Class[Oracle_java::Download]: Scheduling refresh of Class[Oracle_java::Install]
Info: Class[Oracle_java::Install]: Scheduling refresh of Class[Oracle_java::Install::Rpm]
Info: Class[Oracle_java::Install::Rpm]: Scheduling refresh of Package[jre]
Notice: /Stage[main]/Oracle_java::Install::Rpm/Package[jre]/ensure: created
Notice: /Stage[main]/Oracle_java::Install::Rpm/Package[jre]: Triggered 'refresh' from 1 events
Info: Creating state file /opt/puppetlabs/puppet/cache/state/state.yaml
Notice: Applied catalog in 12.76 seconds
```
```
[root@b516b9175d29 /]# java -version
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)
```

**Comment by markfaine** [comment] 2016-12-06 22:16
Yes, it's very strange.  I'm actually seeing it with Archive as a dependency of tomcat but I guess it's the same issue.   If there's anything I could provide that would help you see the issue more clearly let me know.  I know it's frustrating when you can't reproduce something.

```
$ dzdo puppet agent -t --noop
Info: Using configured environment 'dctm_development'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: no parameter named 'provider' at /etc/puppetlabs/code/environments/dctm_development/modules/tomcat/manifests/extras.pp:22 on Archive[catalina-jmx-remote.jar] at /etc/puppetlabs/code/environments/dctm_development/modules/tomcat/manifests/extras.pp:22 on node ndmsdasd1.somedomain
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

**Comment by antoineco** [comment] 2016-12-06 22:16
Could somebody execute this manifest in an environment where the module fails? I would really appreciate if you could run `puppet apply` in debug mode (`-d` flag) and email me the full trace.

```puppet
archive { '/tmp/tomcat.tgz':
  source   => 'http://ftp.fau.de/apache/tomcat/tomcat-9/v9.0.0.M13/bin/apache-tomcat-9.0.0.M13.tar.gz',
  provider => 'curl'
}
```

**Comment by antoineco** [comment] 2016-12-06 22:22
1. [This issue](https://github.com/voxpupuli/puppet-archive/issues/105#issuecomment-219806433) suggests a bug with the Puppet server. This would explain why I can't reproduce in serverless mode.
2. [This other issue](https://github.com/voxpupuli/puppet-archive/issues/225) seems relevant as well.

**Comment by markfaine** [comment] 2016-12-06 22:28
I will try to execute the manifest and send you some results.

**Comment by antoineco** [comment] 2016-12-06 22:31
If the problem is caused by the Puppet master `puppet apply <file.pp>` should succeed on the target machine, but keep failing in agent mode.

**Comment by markfaine** [comment] 2016-12-08 14:42
@antoineco Okay, if I run the manifest you provided using 

```
# puppet apply test/mytest.pp
Notice: Compiled catalog for ndmsdasd1.ndc.nasa.gov in environment dctm_development in 0.15 seconds
Notice: /Stage[main]/Main/Archive[/tmp/tomcat.tgz]/ensure: download archive from http://ftp.fau.de/apache/tomcat/tomcat-9/v9.0.0.M13/bin/apache-tomcat-9.0.0.M13.tar.gz to /tmp/tomcat.tgz  with cleanup
Notice: Applied catalog in 20.35 seconds
```

However, it still fails when I run it normally with agent -t

```
# puppet agent -t
Info: Using configured environment 'dctm_development'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: no parameter named 'provider' at /etc/puppetlabs/code/environments/dctm_development/modules/tomcat/manifests/extras.pp:22 on Archive[catalina-jmx-remote.jar] at /etc/puppetlabs/code/environments/dctm_development/modules/tomcat/manifests/extras.pp:22 on node ndmsdasd1.somedomain
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

```
I also noticed that if I run immediately after restarting the puppet server:

```
root@ndmsdasd1 ~ # puppet agent -t
Info: Using configured environment 'dctm_development'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Could not autoload puppet/type/archive: Could not autoload puppet/provider/archive/curl: Could not find parent provider ruby of curl at /etc/puppetlabs/code/environments/dctm_development/modules/tomcat/manifests/extras.pp:22:3 on node ndmsdasd1.somedomain
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```
Running again after this error message produces the original no parameter named 'provider' message.

**Closed as completed** 2016-12-08 22:16 UTC
Labels: help wanted
