### ISSUE TITLE
Error: Could not set 'file' on ensure: Is a directory @ rb_sysopen - /usr/java/jdk1.8.0_144

### ISSUE THREAD

**Issue by roman-pomyanskiy** [antoineco/aco-oracle_java#44] opened 2017-12-06 14:52 UTC
Hi, 
I'm getting the following error in my Ubuntu 16.04 and module 2.9.1

Notice: /Stage[main]/Oracle_java::Install::Targz/File[/usr/java/jdk1.8.0_144]: Not removing directory; use 'force' to override
Notice: /Stage[main]/Oracle_java::Install::Targz/File[/usr/java/jdk1.8.0_144]: Not removing directory; use 'force' to override
Error: Could not set 'file' on ensure: Is a directory @ rb_sysopen - /usr/java/jdk1.8.0_144 at /etc/puppetlabs/puppet/environments/maxifier/modules/oracle_java/manifests/install/targz.pp:23
Error: Could not set 'file' on ensure: Is a directory @ rb_sysopen - /usr/java/jdk1.8.0_144 at /etc/puppetlabs/puppet/environments/maxifier/modules/oracle_java/manifests/install/targz.pp:23
Wrapped exception:
Is a directory @ rb_sysopen - /usr/java/jdk1.8.0_144
Error: /Stage[main]/Oracle_java::Install::Targz/File[/usr/java/jdk1.8.0_144]/ensure: change from directory to file failed: Could not set 'file' on ensure: Is a directory @ rb_sysopen - /usr/java/jdk1.8.0_144 at /etc/puppetlabs/puppet/environments/maxifier/modules/oracle_java/manifests/install/targz.pp:23
Notice: /Stage[main]/Oracle_java::Install::Targz/File[/usr/java/jdk1.8.0_144/COPYRIGHT]: Dependency File[/usr/java/jdk1.8.0_144] has failures: true
Warning: /Stage[main]/Oracle_java::Install::Targz/File[/usr/java/jdk1.8.0_144/COPYRIGHT]: Skipping because of failed dependencies
Debug: /Stage[main]/Oracle_java::Install::Targz/File[/usr/java/jdk1.8.0_144/COPYRIGHT]: Resource is being skipped, unscheduling all events
Notice: /Stage[main]/Oracle_java::Install::Targz/File[/usr/java/jdk1.8.0_144/LICENSE]: Dependency File[/usr/java/jdk1.8.0_144] has failures: true
Warning: /Stage[main]/Oracle_java::Install::Targz/File[/usr/java/jdk1.8.0_144/LICENSE]: Skipping because of failed dependencies

**Comment by antoineco** [comment] 2017-12-06 20:21
Leftovers from a previous installation maybe?

**Comment by roman-pomyanskiy** [comment] 2017-12-07 08:22
I cloned your module into an internal gitlab and fixed the file resource file { "${oracle_java::install_path}/${oracle_java::longversion}":  in https://github.com/antoineco/aco-oracle_java/blob/master/manifests/install/targz.pp. I add ensure   => directory and this fixed a mistake. Please correct this in your code.

**Comment by antoineco** [comment] 2018-01-20 11:42
Can't reproduce on a fresh Ubuntu 16.04 installation.

**Execution script**

```console
root@9fa2c48f30b7:/# puppet module install aco-oracle_java --version 2.9.2
Notice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...
Notice: Downloading from https://forgeapi.puppet.com ...
Notice: Installing -- do not interrupt ...
/etc/puppetlabs/code/environments/production/modules
└─┬ aco-oracle_java (v2.9.2)
  ├── puppet-archive (v2.2.0)
  └── puppetlabs-stdlib (v4.24.0)
```
```console
root@9fa2c48f30b7:/# puppet apply -te 'include oracle_java'
Info: Loading facts
Info: Loading facts
Notice: Compiled catalog for 9fa2c48f30b7 in environment production in 1.24 seconds
Info: Applying configuration version '1516448299'
Notice: /Stage[main]/Oracle_java::Download/File[/usr/java]/ensure: created
Notice: /Stage[main]/Oracle_java::Download/Archive[/usr/java/jre-8u162-linux-x64.tar.gz]/ensure: download archive from http://download.oracle.com/otn-pub/java/jdk/8u162-b12/0da788060d494f5095bf8624735fa2f1/jre-8u162-linux-x64.tar.gz?AuthParam=[redacted] to /usr/java/jre-8u162-linux-x64.tar.gz and extracted in /usr/java with cleanup
Info: Class[Oracle_java::Download]: Scheduling refresh of Class[Oracle_java::Install]
Info: Class[Oracle_java::Install]: Scheduling refresh of Class[Oracle_java::Install::Targz]
Notice: /Stage[main]/Oracle_java::Install::Targz/File[/usr/java/default]/ensure: created
Info: Creating state file /opt/puppetlabs/puppet/cache/state/state.yaml
Notice: Applied catalog in 11.09 seconds
```

I'm convinced the issue is caused by leftovers from a previous installation, Puppet knows how to manage directory dependencies.

Closing

**Closed as completed by antoineco** 2018-01-20 11:42 UTC
