### ISSUE TITLE
New SSO function leads to failing puppet runs

### ISSUE THREAD

**Issue by noqqe** [antoineco/aco-oracle_java#37] opened 2017-10-24 08:04 UTC
Hi,

since v2.9.X the runs fail. Downgraded to v.2.8.3 makes the module work again

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Could not autoload puppet/parser/functions/oracle_sso: no such file to load -- puppet_x/util at /etc/puppetlabs/code/environments/production/modules/oracle_java/manifests/download.pp:33:17
```

**Comment by antoineco** [comment] 2017-10-24 08:09
Hi @noqqe, could you indicate which Ruby and Puppet client/server versions you're using?

**Comment by noqqe** [comment] 2017-10-24 08:22
Hi @antoineco 

I'm using puppet 4.10.7 on Debian Jessie (PC1) with builtin ruby version 2.1.9p490

**Comment by antoineco** [comment] 2017-10-24 08:54
Alright, and what about the Puppet server version?

I've seen so many issues with environment caching that I can't help asking a stupid question: did you try restarting the Puppet server in order to invalidate your environment's cache?

If yes, I think a simple solution would be to load the Util module using its full path. Eg.

```ruby
# oracle_sso.rb
module Puppet::Parser::Functions
  mod = Puppet::Module.find('oracle_java', Puppet[:environment].to_s)
  require File.join mod.path, 'lib/puppet_x/util'
```

I don't have a Puppet server at hand right now but I'll give it a try this week. Thanks for reporting!

**Comment by noqqe** [comment] 2017-10-24 09:15
Whoops, sorry. 

puppetserver is 2.7.2-1puppetlabs1. And yes, I know what you are talking about :) I've restarted multiple times because of caching

**Comment by paesano2003** [comment] 2017-10-25 21:21
Hello,

This is my first comment ever, so I apologize in advanced if I didn't follow proper etiquette.

Having the same issue here when attempting to apply JDK 8u151 and 8u152, with and without specifying checksum/build/url_code.  Even when specifying the full path to load puppet_x/util.rb inside oracle_sso.rb, it fails with:

```
Error: Could not autoload puppet/provider/package/aptrpm: Operation not permitted @ rb_sysopen - /tmp/puppet20171025-4972-lk6uaw
Error: Facter: error while resolving custom facts in /opt/puppetlabs/puppet/cache/lib/facter/package_provider.rb: Could not autoload puppet/provider/package/aptrpm: Operation not permitted @ rb_sysopen - /tmp/puppet20171025-4972-lk6uaw
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, undefined method `empty?' for #<URI::HTTP:0x446c735f> at /etc/puppetlabs/code/environments/<environment>/modules/oracle_java/manifests/download.pp:33:17 on node <node>
```

I made the following change inside oracle_java/manifests/download.pp (comment out lines) and v2.9.1 of your module works with 8u144. However 8u151/152 throws checksum error because it curls/downloads permission denied page due to not accepting agreement, rather than downloading rpm.
```
  if $oracle_java::oracle_url {
  #  Archive {
  #    source => oracle_sso("${oracle_java::download_url_real}/${oracle_java::filename_real}", $oracle_java::ssousername, $oracle_java::ssopassword)
  #  }
  #} else {
    Archive {
      source => "${oracle_java::download_url_real}/${oracle_java::filename_real}"
    }
  }
```
RHEL 7.3 
ruby 2.0.0p648 (2015-12-16) [x86_64-linux]
puppetserver version: 2.8.0

Thanks very much.

**Comment by antoineco** [comment] 2017-10-26 06:19
@paesano2003 it seems like you're having another issue with some custom fact (package_provider.rb):

`Facter: error while resolving custom facts in /opt/puppetlabs/puppet/cache/lib/facter/package_provider.rb: Could not autoload puppet/provider/package/aptrpm: Operation not permitted @ rb_sysopen`

Regarding the other error:
`undefined method 'empty?' for #<URI::HTTP:0x446c735f> `
I'm not even using such method in the module, so I'm a bit confused. (**edit:** managed to reproduce it)

**Comment by antoineco** [comment] 2017-10-26 10:33
@noqqe @paesano2003 could you both try the referenced PR ☝️  in your environment?

**Comment by antoineco** [comment] 2017-10-26 12:32
Alright I understand the issue now. Puppet Server interprets Ruby code using jruby 1.7.27 (1.9.3p551), I did all my test with Ruby 2+, which has a `uri()` method for HTTPResponse objects.

I'm refactoring my code to play nice with Puppet Server.

**Comment by antoineco** [comment] 2017-11-06 20:39
Everything should work now on the `handle-include-loaderror` branch. I'll try it tomorrow with a fresh Puppet Server, unless someone confirms first :)

**Comment by paesano2003** [comment] 2017-11-06 20:50
@antoineco thanks for the great module and quick turnaround!  Looking forward to the new release.

**Closed as completed** 2017-11-06 23:03 UTC
Labels: bug
